### ISSUE TITLE
Sound of reflection

### ISSUE THREAD

**Issue by LoveIsDarkness** [Albeoris/Memoria#119] opened 2020-05-24 19:23 UTC
Instead of the sound of reflection, the sound of magic is played.
https://yadi.sk/d/Q6Uk40n35-AVeA
There is a reflection sound in this database, but in a game one sound consists of several sounds. I rummaged through all the sounds in the PC version, but never found it. We tried to find a mistake with the programmer, there was a sound error in the logs, we thought that it was him, corrected it by substituting another sound, the error was corrected, but the reflection sound did not play.
The error itself at 0:57
https://youtu.be/3-g9yVk28GQ?t=57
RUS
Вместо звука отражения звучит звук магии.
https://yadi.sk/d/Q6Uk40n35-AVeA
В этой базе есть звук отражения, но в игре один звук состоит из нескольких звуков. Я перерыл все звуки в PC версии, но так и не нашёл его. С программистом пытались найти ошибку, в логах была ошибка звука, думали что это он, исправили её подставив другой звук, ошибка исправилась, но звук отражения так и не проигрался.
Сама ошибка на 0:57
https://youtu.be/3-g9yVk28GQ?t=57

**Comment by Albeoris** [comment] 2020-05-25 08:00
If I hear correctly, then instead of the sound of reflection, the sound of the spell itself is played.
I think if you'll log all the sounds played, you will see a repetition.

Если я слышу правильно, то вместо звука отражения проигрывается звук самого заклинания.
Думаю, стоит залогировать все проигрываемые звуки, и вы увидите повторение.

**Comment by Tirlititi** [comment] 2020-05-31 15:29
After a couple of tests, I might have a fix for that except that I don't know what's the proper sound to use: the method SFX.SoundPlayChant is mainly (uniquely?) used for the sound played with the little "channeling" animation at the start of most spells AND for the reflect sounds (in both cases, there are 3 sounds played together). For the "channeling" animation, the argument "dno" seems to be only "0" (most of the time), "1" (didn't see it) and "2" (for some summons, eg. Bahamut). By design, it can't be "4" or more because that would make the sound ID go to 12 or more which is entering the sound IDs of "SoundPlay" and "StreamPlay". For the "reflect" sounds, the argument "dno" is "3". I think that it is the only case in which it is "3" although I'm not sure and it would require more tests to be 100% sure.

So, here would be the fix:
```
    public static void SoundPlayChant(Int32 dno, Int32 attr, Int32 position)
    {
        Int32 num = (dno & 16777215) * 3 + SFX.seChantIndex;
        if ((dno & 16777215) == 3)
            SoundLib.PlaySfxSound(REFLECT_SOUND_ID[ SFX.seChantIndex % 3 ], 1f, 0f, 1f); // Run a reflect sound, assuming that it consists of 3 sound pieces
        else
            SoundLib.PlaySfxSound(num, 1f, 0f, 1f); // Run the usual chant sound
        SFX.seChantIndex++;
        for (Int32 i = 0; i < SFX.MAX_INDEX; i++)
        {
            if (SFX.channel[i, 0] == -1)
            {
                SFX.channel[i, 0] = attr;
                SFX.channel[i, 1] = num;
                break;
            }
        }
    }
```
If there is only one sound for the reflect, you can use that instead:
```
        if ((dno & 16777215) == 3) {
            if (SFX.seChantIndex % 3 == 0)
                SoundLib.PlaySfxSound(REFLECT_SOUND_ID, 1f, 0f, 1f); // Run the reflect sound
        } else {
            SoundLib.PlaySfxSound(num, 1f, 0f, 1f); // Run the usual chant sound
        }
```

**Comment by LoveIsDarkness** [comment] 2020-05-31 16:42
I tried several times to find the sound of reflection, I understand that it could consist of three sounds, as a result I found a pack with sounds on the Internet and there was a sound of reflection, only it consists of one sound.

convert
https://yadi.sk/d/pcrFbRotWL1nHw
original
https://yadi.sk/d/_m4CEZ4Op15azg

**Comment by DoomOyster** [comment] 2020-06-11 21:19
I also could not find the reflect sound in the game files. Taking some wild guesses here: Could we pack the conversion LoveIsDarkness provided above into p0data62? There are many 78kb (79344) sounds that seem to have no sound at all. File se020260 is the sound to cast reflect. se020261 and se020262 have no sound. Can we check that these indices are unused?

   {
      "name": "Sounds02/SE02/se020260",
      "soundIndex": "182",
      "type": "SoundEffect"
    },
    {
      "name": "Sounds02/SE02/se020261",
      "soundIndex": "170",
      "type": "SoundEffect"
    },
    {
      "name": "Sounds02/SE02/se020262",
      "soundIndex": "150",
      "type": "SoundEffect"
    },

**Comment by LoveIsDarkness** [comment] 2020-06-12 16:32
You can pack the sound, it's just not clear how the game gives out indices to sounds.

**Comment by snouz** [comment] 2020-06-12 16:33
I just unpacked all sounds in the game and put the one after the other in ableton live, and listened to every single one of them, even twice for the magic folder (se02). I can confidently say the original PSX sound is not present in the steam game. https://youtu.be/rZA02v56OSs?t=59

Contrary to a previous comment, none are empty (it's your player cropping)

**Comment by DoomOyster** [comment] 2020-06-14 02:19
So, add the asset to p0data62/assets/resources/sounds/sounds02/se02/se020387.akb
Add to soundeffectmetadata.txt
{
"name": "Sounds02/SE02/se020387",
"soundIndex": "350", //appears to be unused
"type": "SoundEffect"
},
Call the sound by 350 in Tirlititi's code above

**Comment by Tirlititi** [comment] 2020-06-15 17:37
Here is a fix that works with the latest update (to be improved): https://www.dropbox.com/s/s26l8i2hlue41ni/PC_ReflectSoundFix.zip?dl=1

I have to improve it because the volume of the file given by LovelsDarkness is way too low (I increased the volume in the C# code to compensate) and it doesn't sound to be exactly the correct sound to me. At least it works in the sense that it plays the external sound instead of a duplicate of the SFX sounds (by default, the lastest version of Memoria seeks for the sound with index "350" and plays no sound if it cannot be found).

**Comment by LoveIsDarkness** [comment] 2020-06-15 18:08
And this is not the only moment when the sound was lost when disassembling the game. Here is another example, there is no sound, and possibly a few sounds (when they show the planet), so the previous sound is repeated.
at 4:21
https://youtu.be/3-g9yVk28GQ

and even this happens at the end of the game, when Zidane covers Kuja with himself, the same sound of the root strike is repeated.

**Comment by LoveIsDarkness** [comment] 2020-08-24 19:55
Probably the game sees that there is sound, so it does not reproduce the sound of magic, instead of the sound of reflection, but there is no sound of reflection itself, or it is not heard at all. 44100Hrz

**Comment by DV666** [comment] 2022-04-02 16:12
Hi !

I propose you a solution to correct this little problem : indeed, I just remembered that one of the spells of the game uses sound files which are very close to the Reflect when it bounces... or even, I wonder if they are simply identical!

So I propose the following modification, without involving adding a new sound file :)

```
	public static void ExecuteLoop()
	{
		foreach (SFXChannel channel in SFXChannel.CurrentPlay.Values)
			channel.frame++;
		foreach (SFXChannel reflect in SFXChannel.CurrentPlayReflect)
		{
			// Reflect Sound Effect
			if (reflect.frame == 0)
			{
				SoundLib.PlaySoundEffect(1248, 1.5f, 0f, 1f); // Sound used by Electricity (Mind_Blast)
				SoundLib.PlaySoundEffect(1249, 1.5f, 0f, 1f); // Sound used by Electricity (Mind_Blast)
				SoundLib.PlaySoundEffect(1250, 1.5f, 0f, 1f); // Sound used by Electricity (Mind_Blast)
			}
			reflect.frame++;
		}
	}
```
	
You can find a small video to better show you the thing ^^ => https://www.youtube.com/watch?v=ijGZ-_BrY1k (used with pre-release SFX Rework)

What do you think ? :)

**Closed** 2022-04-29 01:39 UTC
Labels: bug, help wanted, _🔊
