### ISSUE TITLE
'Permanent' WideScreen

### ISSUE THREAD

**Issue by polt13** [Albeoris/Memoria#100] opened 2020-05-16 10:52 UTC
Hi, 
Wide screen seems to be on and off for me so far, in the open world it works as intended everytime, when entering buildings or towns etc it works randomly, for some places it works and for some it doesn't. I am using the latest Memoria build and Moguri Beta. I'm not sure, however, if that's an issue with these two being incompatible or a glitch with Memoria (i've seen other WideScreen Issues opened on this repo, like part of characters showing on the Black Bars).  Are the black bars the expected behavior in towns perhaps?

Thanks a lot!

**Comment by snouz** [comment] 2020-05-16 16:32
Duplicate of #96

**Closed** 2020-05-16 16:36 UTC
