### ISSUE TITLE
controller setting bug

### ISSUE THREAD

**Issue by i5JvSp4AY2CxuA7e** [Albeoris/Memoria#385] opened 2024-04-21 00:03 UTC
When I switch the controls to custom, the buttons briefly flash and the cursor is stuck at the buttom on an invisible setting until I press start. After that I can change the buttons until I open the setting again where it repeats the same progress. Also the buttons I select are wrong, if I select X it changes to A for example.

https://imgur.com/a/2wy9tw2

**Comment by snouz** [comment] 2024-04-21 00:39
Thanks for reporting, I really can't reproduce, I tested with the latest available Memoria release (https://github.com/Albeoris/Memoria/releases), is this the one you have installed? Or maybe it's unmodified Moguri? What's your system and controller?

**Comment by SamsamTS** [comment] 2024-04-21 23:45
I do remember I encountered something like that and fixed in https://github.com/Albeoris/Memoria/pull/261
Can you test with this release https://github.com/SamsamTS/Memoria/releases/tag/v2023.09.09 and confirm it is fixed?

**Comment by snouz** [comment] 2024-04-22 00:08
I was thinking the same, since this commit is just after the latest release (which begins to age quite a bit)

**Comment by SamsamTS** [comment] 2024-04-22 13:27
> It works! Btw is there a setting to turn off the remapping that memoria automatically does? (switching A and B)

Not that I'm aware of. I believe the consensus was that most people wanted it to be "western style" so they made it the default? I wasn't around at that time so I don't really know. In any case controls can be remapped in the in-game options.

**Closed as completed** 2024-04-22 13:53 UTC
Labels: - Bug (gameplay) -, X Need more information
