### ISSUE TITLE
Bug visual - Character & npc with dialog not moving up and down when riding gondola

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#843] opened 2024-09-19 01:21 UTC
https://github.com/user-attachments/assets/31105506-05b3-40e2-8669-8a489f273e4f

Memoria.ini file :

[Mod]
FolderNames = "MoguriMain", "MoguriVideo"
Priorities = "MoguriVideo", "MoguriMain"
UseFileList = 1
MergeScripts = 0

[Font]
Enabled = 0
Names = "Arial", "Times Bold"
Size = 24

[Audio]
MusicVolume = 100
SoundVolume = 75
MovieVolume = 100
PriorityToOGG = 0
Backend = 1

[Graphics]
Enabled = 1
BattleFPS = 60
BattleTPS = 15
FieldFPS = 60
FieldTPS = 30
WorldFPS = 60
WorldTPS = 20
MenuFPS = 60
MenuTPS = 60
BattleSwirlFrames = 115
WidescreenSupport = 1
SkipIntros = 0
GarnetHair = 0
TileSize = 64
AntiAliasing = 8
CameraStabilizer = 85
FieldSmoothTexture = 2
WorldSmoothTexture = 2
BattleSmoothTexture = 2
ElementsSmoothTexture = 2
SFXSmoothTexture = 2
UISmoothTexture = 2

[Control]
Enabled = 1
DisableMouse = 7
DialogProgressButtons = "Confirm"
WrapSomeMenus = 1
BattleAutoConfirm = 1
TurboDialog = 1
SoftReset = 1
PSXScrollingMethod = 1
PSXMovementMethod = 1
AlwaysCaptureGamepad = 1

[AnalogControl]
Enabled = 1
StickThreshold = 10
MinimumSpeed = 5
UseAbsoluteOrientation = 0

[Battle]
Enabled = 1
SFXRework = 1
Speed = 0
NoAutoTrance = 0
EncounterInterval = 960
EncounterInitial = -1440
PersistentDangerValue = 0
PSXEncounterMethod = 0
AutoPotionOverhealLimit = -1
GarnetConcentrate = 1
SelectBestTarget = 1
BreakDamageLimit = 0
ViviAutoAttack = 0
CountersBetterTarget = 0
LockEquippedAbilities = 0
FloatEvadeBonus = 0
AccessMenus = 0
AvailableMenus = "Equip", "SupportingAbility"
CustomBattleFlagsMeaning = 0
StatusDurationFormula = ContiCnt * (IsNegativeStatus ? 8 * (60 - TargetSpirit) : (IsPositiveStatus ? 8 * TargetSpirit : 4 * (60 - TargetSpirit)))
StatusTickFormula = OprCnt * (IsNegativeStatus ? 4 * TargetSpirit : 4 * (60 - TargetSpirit))
SpeedStatFormula = Min(50, SpeedBase + Level / 10 + (SpeedBonus >> 5))
StrengthStatFormula = Min(99, StrengthBase + Level * 3 / 10 + (StrengthBonus >> 5))
MagicStatFormula = Min(99, MagicBase + Level * 3 / 10 + (MagicBonus >> 5))
SpiritStatFormula = Min(50, SpiritBase + Level * 3 / 20 + (SpiritBonus >> 5))
MagicStoneStockFormula = Min(99, MagicStoneBase + Level * 4 / 10 + (MagicStoneBonus >> 5))
TranceDecreaseFormula = (300 - Level) / Spirit * 10

[Icons]
Enabled = 1
HideCursor = 0
HideCards = 0
HideExclamation = 0
HideQuestion = 0
HideBeach = 0
HideSteam = 0

[Cheats]
Enabled = 1
Rotation = 1
Perspective = 1
SpeedMode = 0
SpeedFactor = 3
SpeedTimer = 0
BattleAssistance = 0
Attack9999 = 0
NoRandomEncounter = 0
MasterSkill = 1
LvMax = 1
GilMax = 1

[Hacks]
Enabled = 1
AllCharactersAvailable = 0
RopeJumpingIncrement = 1
SwordplayAssistance = 1
FrogCatchingIncrement = 1
HippaulRacingViviSpeed = 33
StealingAlwaysWorks = 2
DisableNameChoice = 0
ExcaliburIINoTimeLimit = 0

[TetraMaster]
Enabled = 1
TripleTriad = 0
ReduceRandom = 0
MaxCardCount = 100
DiscardAutoButton = 1
DiscardAssaultCards = 0
DiscardFlexibleCards = 1
DiscardMaxAttack = 224
DiscardMaxPDef = 255
DiscardMaxMDef = 255
DiscardMaxSum = 480
DiscardMinDeckSize = 10
DiscardKeepSameType = 1
DiscardKeepSameArrow = 0
DiscardExclusions = 56, 75, 76, 77, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 99, 100

[Interface]
BattleRowCount = 4
BattleColumnCount = 1
BattleMenuPosX = -500
BattleMenuPosY = -360
BattleMenuWidth = 650
BattleMenuHeight = 280
BattleDetailPosX = 500
BattleDetailPosY = -422
BattleDetailWidth = 672
BattleDetailHeight = 208
MinimapPreset = 1
MinimapOffsetX = 0
MinimapOffsetY = 0
PSXBattleMenu = 1
ScanDisplay = 1
BattleCommandTitleFormat = 
BattleDamageTextFormat = 
BattleRestoreTextFormat = 
BattleMPDamageTextFormat = 
BattleMPRestoreTextFormat = 
MenuItemRowCount = 8
MenuAbilityRowCount = 6
MenuEquipRowCount = 5
MenuChocographRowCount = 5
FadeDuration = 40
SynthIngredientStockDisplayed = 1
DisplayPSXDiscChanges = 1

[Fixes]
Enabled = 1
KeepRestTimeInBattle = 1

[SaveFile]
DisableAutoSave = 0
AutoSaveOnlyAtMoogle = 0
SaveOnCloud = 0

[Speedrun]
Enabled = 0
SplitSettingsPath = 
LogGameTimePath = 

[Debug]
Enabled = 0
SigningEventObjects = 0
StartModelViewer = 0
StartFieldCreator = 0
RenderWalkmeshes = 0

[Export]
Enabled = 0
Path = %StreamingAssets%
Languages = "US", "UK", "JP", "ES", "FR", "GR", "IT"
Text = 1
TextFileFormat = .strings
Graphics = 1
Audio = 1
Field = 0
Battle = 0

[Import]
Enabled = 0
Path = %StreamingAssets%
Text = 1
Audio = 1
Graphics = 1
Field = 0

[Shaders]
Enabled = 0
Shader_Field_Realism = 0
Shader_Field_Toon = 0
Shader_Field_Outlines = 0
Shader_Battle_Realism = 0
Shader_Battle_Toon = 0
Shader_Battle_Outlines = 0

**Comment by snouz** [comment] 2024-09-19 13:00
It's a duplicate of #434, but thanks for reporting anyway, don't hesitate if you see some more problems

**Closed by snouz** 2024-09-19 13:00 UTC
Labels: X Duplicate

**Comment by yisandind** [comment] 2024-09-19 16:32
oh ok, sorry. I searched for it with the keyword "gondola" instead of "boat".

**Comment by snouz** [comment] 2024-09-19 17:01
> oh ok, sorry. I searched for it with the keyword "gondola" instead of "boat".

Don't worry for duplicates, it's my job to know that, continue reporting if you see anything, you've brought up a few things we hadn't notice yet
