### ISSUE TITLE
[Req] Linux port

### ISSUE THREAD

**Issue by jefferyrlc** [Albeoris/Memoria#86] opened 2019-07-05 08:00 UTC
Having Memoria able to run FFIX natively in Linux would be great. Right now you can play the Steam version with proton, but my attempts to run Memoria with proton have been fruitless.

**Comment by Albeoris** [comment] 2020-05-20 09:59
I close it, since no one else came with this problem, and I have no way to reproduce and fix it.

**Closed by Albeoris** 2020-05-20 09:59 UTC
Labels: enhancement, help wanted, need more information

**Comment by jefferyrlc** [comment] 2020-05-20 10:26
It's not a bug to reproduce. It was a feature request for a native port of the engine to Linux.

**Comment by yaomtc** [comment] 2020-11-16 20:28
@jeffreyrlc, I can run the Moguri Mod game fine with this version of Proton which uses this engine.

https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.11-GE-3-MF

I can't get FF9_Launcher.exe to start, I just get an error. But this doesn't prevent me from playing the game, just changing settings like disabling the reorchestrated soundtrack. Though that part doesn't really apply to Memoria, but rather whoever made the custom launcher for Moguri Mod.
