### ISSUE TITLE
Widescreen support for 16/10 and ultra-wide screens

### ISSUE THREAD

**Issue by Deleted-Account** [Albeoris/Memoria#197] opened 2022-05-02 10:45 UTC
I'm using a 3440x1440 widescreen with this mod and SRWE(Simple Runtime Window Editor) tool to make this game borderless and wider.

Some scenes worked fine and amazingly immersive.
![image](https://user-images.githubusercontent.com/48331538/166221485-619c465a-c916-473c-8899-529c5a2f1d34.png)

Some of them did not, just stuck in 16:9 or 4:3. (anyways, some of them, if you press START, you can see the the game has wide enough background  to render in 21:9 or even wider)
![image](https://user-images.githubusercontent.com/48331538/166221551-8c6e2ad7-b840-4d8b-9332-3f4fabe22fae.png)
![image](https://user-images.githubusercontent.com/48331538/166221576-17d0f763-0865-4b11-a6be-17ca90498c6f.png)

So, it there an way to force this game to render more widely?
I don't mind if the 3D models standing outside the black background at some scenes though may look wired.

Thanks for your great work.

**Comment by snouz** [comment] 2024-01-14 13:54
The problem is that it would require to code a whole new system, as right now you have widescreen or not, it's a true or false. Then it would require to hardcode a screen limit for all screens, so this is a big endeavor. Also, the problem is owning a 16/10 or larger screen, which I don't.
Can someone with this screen can at least confirm that widescreen works when you select a 16/9 resolution? Can you still play with top and bottom bars? Are you locked into using 4/3? Does it work with windowed mode?

**Comment by snouz** [comment] 2024-01-14 14:16
I'm closing this as: showing more of the screen is too complex and not worth it IMO, as it would not improve the experience while switching between narrow and widescreen is already a big immersion breaker for some people.

Duplicate because Ultra widescreen support is already a subject of #186

**Closed by snouz** 2024-01-14 14:16 UTC
Labels: X Duplicate, - Feature request -, X Won't do, X Need more information, Screen size 🖥️
