### ISSUE TITLE
D-Pad defect on some controllers (PS4...)

### ISSUE THREAD

**Issue by tbartel** [Albeoris/Memoria#110] opened 2020-05-21 17:58 UTC
After installing Memoria, my Xbox 360's D-Pad no longer works to control the characters or to navigate the UI. This happens even if I disable Analog in the .ini file.

**Comment by Albeoris** [comment] 2020-05-21 20:09
https://www.nexusmods.com/finalfantasy9/mods/3?tab=bugs
This is the same problem, right?

**Comment by snouz** [comment] 2020-05-21 20:30
I cannot reproduce the problem.

I tested with both an official 360 controller and official xbox one controller on W10, and on both, the D-pad is working in the game and in menus.

**Comment by tbartel** [comment] 2020-05-21 20:46
@Albeoris I'm not sure if it's the same bug, though it doesn't sound like it, as I'm not having any issues with swapped buttons.

@snouz At least one other person has reported having this same issue in the Moguri forum thread; see point 2 [here](https://forums.qhimm.com/index.php?topic=19225.msg278526#msg278526). 

For what it's worth, I'm using Steam to launch the game and have the overlay enabled. Essentially, I've left the default Steam configuration, but perhaps Steam's built-in controller mapping functionality is somehow involved?

Disabling analog via the following setting does _not_ resolve it:
```
[AnalogControl]
Enabled = 0
```

**Comment by Albeoris** [comment] 2020-05-21 20:56
Does the Steam Overlay in the game work correctly for you?

**Comment by e2zippo** [comment] 2020-05-24 09:26
I have the same problem, even though analog is disabled in memoria.ini my dpad isn't working.
I have a 8bitDo SN30 Pro + and I use Xinput.

**Comment by snouz** [comment] 2020-05-24 18:59
Glenn Seto:

"The d-pad issue (which I've seen people comment may also affect shoulder buttons?) went away for me, when I configured the game's properties in Steam, disabling the Steam Overlay and forcing Per-Game Input Settings on"

**Comment by e2zippo** [comment] 2020-05-25 15:14
Confirmed that disabling the Steam Overlay and forcing Per-Game Input Settings on fixes it.

**Comment by tbartel** [comment] 2020-05-25 16:43
I can confirm the above fixed it for me as well. Closing this as a result.

**Comment by snouz** [comment] 2020-05-25 18:55
Why do you close it? the problem is apparently still present and this is just a workaround

**Comment by e2zippo** [comment] 2020-05-25 19:21
Yeah, workaround shouldn't be needed. It's nice that there is a workaround but issue still remains.

**Comment by sepam21** [comment] 2020-06-06 18:09
I suspect the reason is Scaled Battle UI. 
Can somebody check it out?

**Comment by e2zippo** [comment] 2020-06-06 22:10
> I suspect the reason is Scaled Battle UI.
> Can somebody check it out?

I have the issue without the Scaled Battle UI.

**Comment by snouz** [comment] 2020-06-27 22:08
Maybe we can use this to help fix this problem?

https://www.reddit.com/r/Unity3D/comments/1syswe/ps4_controller_map_for_unity/
https://github.com/pbhogan/InControl

Don't know if I'm able to do that, and I don't own a ps4 controller, but if someone can...

**Comment by Tirlititi** [comment] 2020-07-18 14:08
I have a PS4 controller and looked at it, and it really seems that the "work-around trick" is the only proper solution. For what I understand:
1) The "DPadX/Y" axes can only be used if they were configured in UnityEditor, which they were not, so there's no way to get them (I've tried "UnityEngine.Input.GetAxis" with many names without any luck),
2) The "[Gamepad](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.Gamepad.html)" class should have been the way to do it, but the Unity version used by the game doesn't have it (apparently, Unity v3.5 misses it or have it somewhere else). Instead, they use the API from XInputDotNetPure.dll that also has a GamePad class but simpler (no [DualShockGamepad](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.DualShock.DualShockGamepad.html) subclass for instance) and doesn't recognize the PS4 controllers ("XInputDotNetPure.GamePad.GetState(PlayerIndex).IsConnected" returns false whichever PlayerIndex is given; the analog stick directions are properly catched but using "UnityEngine.Input.GetAxis" instead).

I am afraid that having a fix without any configuration from the user's end would require upgrading the game's UnityEngine or XInputDotNetPure.

**Comment by barkermn01** [comment] 2022-08-17 21:53
@Tirlititi I know this is old but the problem is still there and I have problems with the PS5 controller as well, apparently we can remove XInputDotNetPure and use Incontrol instead.

https://forum.unity.com/threads/incontrol-input-and-cross-platform-controller-support-for-unity-made-easy.257619/

**Comment by Tirlititi** [comment] 2022-08-17 22:18
> Requires Unity 4.5+

Unfortunatly, the game was compiled with Unity 3.5.

The main solution for using controllers properly is to enable "Fix Steam Overlay" on the launcher, which allows the player to use Steam's custom controller configuration (without the overlay, that Steam feature cannot be used). With that external way to remap the buttons, a proper configuration can be done. Now every button and pad works perfectly fine on my end.

Note that the option "Fix Steam Overlay" must be disabled when updating the ``FF9_Launcher.exe``; it is best to disable that option, then run the patcher then re-enable the option.

I'm afraid the workaround solutions are still the only solutions.

**Comment by snouz** [comment] 2024-02-19 10:42
Must be solved by https://github.com/Albeoris/Memoria/pull/261 according to SamsamTS

**Closed by snouz** 2024-02-19 10:42 UTC
Labels: - Feature request -, Question/Help ☝️, KB 🕮, Controller 🎮
